version: "3.8"

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5150:5150"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      # Database connection will be via Supabase URL in .env.prod
      # No local database service needed

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    command: npm run build && npm run preview
