version: "3.8"

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "5051:5051"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    command: npm run build && npm run preview
