name: Deploy Frontend to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-22.04


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup frontend environment
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > frontend/.env

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Upload frontend dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "frontend/dist/*"
          target: "/var/www/daily-racing-game/"
          debug: true
          timeout: 120s

      - name: Deploy backend via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/daily-racing-game
            git pull origin main
            npm install
            cd /var/www/daily-racing-game/backend
            pm2 restart dailyracer_backend || pm2 start npm --name dailyracer_backend -- start

            cd /var/www/daily-racing-game/frontend
            pm2 restart dailyracer_frontend || pm2 start serve --name dailyracer_frontend -- dist -l 5173
            
            pm2 save
